// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef Credits_h
#define Credits_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Return_Button.H>

class CreditScreen {
public:
  CreditScreen();
  Fl_Window *fWindow;
  Fl_Output *fOutput;
private:
  void cb_Close_i(Fl_Return_Button*, void*);
  static void cb_Close(Fl_Return_Button*, void*);
public:
  void Show();
};
#endif
