// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef Error_h
#define Error_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <stdarg.h>
#include <stdio.h>
#include <GL/glfw.h>
#include "../modes.h"
#include <FL/Fl_Output.H>
#include <FL/Fl_Return_Button.H>
#include <stdlib.h>

class ErrorDialog {
public:
  ErrorDialog(const char *fmt, ...);
  Fl_Window *fWindow;
private:
  void cb_Exit_i(Fl_Return_Button*, void*);
  static void cb_Exit(Fl_Return_Button*, void*);
};
#endif
