// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef HelpDialog_h
#define HelpDialog_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Return_Button.H>

class HelpDialog {
public:
  HelpDialog();
  Fl_Window *fWindow;
private:
  void cb_Close_i(Fl_Return_Button*, void*);
  static void cb_Close(Fl_Return_Button*, void*);
};
#endif
