// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef OptionsDialog_h
#define OptionsDialog_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "../Options.h"
#include <FL/Fl_Group.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Check_Button.H>
#include "../SoundControl.h"
#include "../primitives.h"
#include <FL/Fl_Slider.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
#include "HelpDialog.h"
#include <GL/glfw.h>
#include <stdlib.h>
#include "../modes.h"

class OptionsDialog {
public:
  OptionsDialog();
  Fl_Double_Window *fWindow;
  Fl_Check_Button *fMusic;
private:
  void cb_fMusic_i(Fl_Check_Button*, void*);
  static void cb_fMusic(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *fPing;
private:
  void cb_fPing_i(Fl_Check_Button*, void*);
  static void cb_fPing(Fl_Check_Button*, void*);
public:
  Fl_Group *fGraphicsTab;
  Fl_Slider *fPerformanceSlider;
  Fl_Choice *fGraphicMode;
  Fl_Check_Button *fFullScreenMode;
  Fl_Value_Slider *fAmbientLight;
  Fl_Check_Button *fSmoothTerrain;
  Fl_Check_Button *fMergeNormals;
  Fl_Check_Button *fAddNoise;
  Fl_Check_Button *fDynamicShadows;
private:
  void cb_Ok_i(Fl_Return_Button*, void*);
  static void cb_Ok(Fl_Return_Button*, void*);
  void cb_Help_i(Fl_Button*, void*);
  static void cb_Help(Fl_Button*, void*);
  void cb_Quit_i(Fl_Button*, void*);
  static void cb_Quit(Fl_Button*, void*);
  void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
};
#endif
